image: node:22

stages:
  - install
  - build
  - deploy

cache:
  key: pnpm-store
  paths:
    - .pnpm-store

variables:
  PNPM_HOME: /pnpm
  PATH: $PNPM_HOME:$PATH

before_script:
  - corepack enable
  - corepack prepare pnpm@10.11.1 --activate
  - pnpm config set store-dir .pnpm-store

install:
  stage: install
  script:
    - pnpm install --frozen-lockfile

build:
  stage: build
  script:
    - pnpm run build
  artifacts:
    paths:
      - .open-next
      - .next
      - worker.js
      - dist

deploy:
  stage: deploy
  environment: production
  script:
    - pnpm exec wrangler deploy
  only:
    - main
